# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            BitShares Committee
tagline:          'BitShares Committee Site'
description:      'News, proposals, suggestions & notifications from the BitShares Committee.'
url:              https://bitshares-committee.github.io
baseurl:          /
repository:       'bitshares-committee/github.com'
author:
  name:           'BitShares Committee'
  url:            https://github.com/bitshares-commitee

paginate:         6

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/bitshares-committee/bitshares-committee.github.io
